

CREATE TABLE TALUNO	(

			COD_ALUNO INTEGER NOT NULL,
			NOME VARCHAR(30),
			CIDADE VARCHAR2(30),
			CEP VARCHAR(10),
			PRIMARY KEY (COD_ALUNO)
);

SELECT * FROM TALUNO;

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (1, 'MARCIO','NOVO HAMBURGO','93000');

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (2, 'ROBERTO','TAUBATE','73000');

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (3, 'MARIA','CALIFORNIA','60000');


CREATE TABLE TCURSO (
         COD_CURSO INTEGER NOT NULL PRIMARY KEY,
         NOME VARCHAR(30),
         VALOR NUMBER(8,2),
         CARGA_HORARIA INTEGER

);

   SELECT * FROM TCURSO;

INSERT INTO TCURSO VALUES (1,'WHATS',600,30);
INSERT INTO TCURSO VALUES (2,'INSTA',599,25);
INSERT INTO TCURSO VALUES (3,'FACE',499,100);


CREATE TABLE TCONTATO (
              COD_CONTRATO INTEGER NOT NULL PRIMARY KEY,
              DATA DATE,
              COD_ALUNO INTEGER,
              TOTAL NUMBER(8,2),
              DESCONT0 NUMBER(5,2)
);

SELECT * FROM TCONTATO


INSERT INTO TCONTATO VALUES(1, SYSDATE, 1, 400, 20);
INSERT INTO TCONTATO VALUES(2, SYSDATE, 2, 400, 20);
INSERT INTO TCONTATO VALUES(3, SYSDATE, 3, 400, 20);
INSERT INTO TCONTATO VALUES(4, SYSDATE -5, 2, 400, 20);





CREATE SEQUENCE  SEQ_ALUNO START WITH 4;


INSERT INTO TALUNO VALUES (SEQ_ALUNO.NEXTVAL, 'MARIA','CALIFORNIA','60000');


SELECT * FROM TALUNO;



COMMIT;



DELETE FROM TALUNO WHERE COD_ALUNO = 6;



ROLLBACK;





CREATE TABLE TITEM (

        COD_ITEM INTEGER NOT NULL PRIMARY KEY,
        COD_CURSO INTEGER,
        COD_CONTRAT0 INTEGER,
        VALOR NUMBER(8,2)

);

INSERT INTO TITEM VALUES(1,2,4,500);

INSERT INTO TITEM VALUES(2,5,9,200);


CREATE SEQUENCE SEQ_TITEM START WITH 3;

INSERT INTO TITEM VALUES(SEQ_TITEM.NEXTVAL, 3 , 5 , 800);

SELECT * FROM TITEM;





 CREATE TABLE PART (
     COD_PEAPLE INTEGER NOT NULL PRIMARY KEY,
     NAME VARCHAR(30),
     AGE NUMBER,
     CITY VARCHAR(30)
);
  CREATE SEQUENCE SEQ_PART START WITH 1;


   INSERT INTO PART(COD_PEAPLE,NAME,AGE,CITY) VALUES(SEQ_PART.NEXTVAL,'FABIO',23,'BARREIRO');



         UPDATE PART SET AGE = 17 WHERE COD_PEAPLE = 2;




SELECT * FROM PART;




CREATE TABLE WORK (
    COD_JOB INTEGER NOT NULL PRIMARY KEY, JOB_NAME VARCHAR(20), TIME_D NUMBER(8,2) );

      INSERT INTO WORK VALUES(1,PROFESSOR, 8);


SELECT * FROM WORK;



CREATE TABLE DATA (
   COD_DATA INTEGER NOT NULL PRIMARY KEY, DATE_BORN DATE );

SELECT * FROM DATA;


 COMMIT;